### PR TITLE
🐛 Debug snapshot object storage

### LINKED ISSUE #42: Store the snapshot object in memory locally
The current application seems to store all the studies even from the past releases since the memory cache in the application is global. In addition, when failed, it does not flush out the scraped data in memory. It needs to be fixed so as to locally store only studies in a specific release.

### PR DESCRIPTION
**Pull request by liberaliscomputing**
This PR close #42.

The following logics are added:

1. Declare a `let snapshot;` variable when spun up
2. Assign an empty object `{}` to the variable when initialized
3. Flush out the variable by assigning an empty object `{}` when published, failed, or cancelled

### CODE REVIEW

File: routes/tasks.js [hunk 1]
```diff
@@ -84,8 +82,8 @@ router.post('/', async (req, res) => {
   return res.status(200).json(await get_status(task_id));
 });
 
-// define a snapshot cache
-const snapshot = {};
+// declare a snapshot cache
+let snapshot;
```
Comment (dankolbman) [inline routes/tasks.js]: It looks like you are storing the snapshot in memory for a release where the snapshot here is an object containing a dump of each study.

This means that two simultaneous snapshots runs will collide with each other here, since it's shared memory. Perhaps you'd be better off storing each release inside its own object in the snapshot object?
```
let snapshot = {
    RE_00000001: { ... },
    RE_00000002: { ... },
}
```

And then when you finish uploading the snapshot to S3, you can do
```
snapshot[releaseId] = {}
```

That way, you won't interfere with any other running tasks.

Comment (liberaliscomputing) [reply routes/tasks.js]: I initially imagined that there will be barely cases where multiple releases race against each other since the release coordinator processes one release per time. As you pointed out, however, there could be some cases where multiple people kicks in releases at the same time. I will revert the declaration of the snapshot object (`let snapshot;`) back to `const snapshot = {}`; and every action of `initialize` will create a nested object with its release ID as a key (snapshot[release_id] = {};). When cancelled, failed, or staged, only the nested object with the release ID will be flushed out (`delete snapshot[release_id];`).

File: routes/tasks.js [hunk 2]
```diff
@@ -116,6 +136,10 @@ const initialize = (task_id, release_id) => {
     state: 'pending',
   };
 
+  // initialize a release snapshot
+  snapshot[release_id] = {};
```
Comment (dankolbman) [inline routes/tasks.js]: What is `release_id` here?
